USE soundvibe;

CREATE TABLE users (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE artists (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE songs (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    artist_ID INT,
    album VARCHAR(255),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (artist_ID) REFERENCES artists(ID)
);

CREATE TABLE playlists (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    user_ID INT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_ID) REFERENCES users(ID)
);

CREATE TABLE likes (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    user_ID INT,
    song_ID INT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_ID) REFERENCES users(ID),
    FOREIGN KEY (song_ID) REFERENCES songs(ID)
);

CREATE TABLE listen_history (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    user_ID INT,
    song_ID INT,
    listened_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_ID) REFERENCES users(ID),
    FOREIGN KEY (song_ID) REFERENCES songs(ID)
);